### PR TITLE
Expand backend equivalence testing

### PR DESCRIPTION
**Pull request by windiana42**
@FelipeNuti @NMAC427 we will continue modifying the branch here for merge with main branch

# Checklist

- [x] Added a `CHANGELOG.rst` entry

### CODE REVIEW

**Comment by windiana42** [comment]
@NMAC427 do we already have an example of an optional dependency with poetry in the repos?

**Comment by NMAC427** [comment]
> @NMAC427 do we already have an example of an optional dependency with poetry in the repos?

Yes we do: https://github.com/pydiverse/pydiverse.pipedag/blob/main/pyproject.toml#L43
This is the appropriate poetry documentation: https://python-poetry.org/docs/pyproject/#extras

**Comment by windiana42** [comment]
I would not yet state in CHANGELOG.rst that we support bigquery. That will be the next step after activating github actions for it.

**Comment by windiana42** [comment]
Most of the work of this PR stays deactivated. But I would still like to merge to not lose it.

**Comment by windiana42** [comment]
This PR also includes harmonization with CI system and pull requests of pipedag.

**Pull request merged**
